"""eta endpoint base

Revision ID: 4499e0f7183c
Revises: 95c89ee2d0f7
Create Date: 2025-05-31 13:20:42.070973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4499e0f7183c'
down_revision: Union[str, None] = '95c89ee2d0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
