"""add latitude longitude to customer

Revision ID: 95c89ee2d0f7
Revises: a3725a419ce0
Create Date: 2025-05-31 13:10:36.743287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c89ee2d0f7'
down_revision: Union[str, None] = 'a3725a419ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('customers', sa.Column('longitude', sa.Float(), nullable=False))
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('customers', 'longitude')
    op.drop_column('customers', 'latitude')
    # ### end Alembic commands ###
